import type { ToolInfo } from './types';

export function exportAsJSON(tools: ToolInfo[]): string {
  const data = tools.map((t) => ({
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema ? safeParse(t.inputSchema) : undefined,
    annotations: t.annotations,
  }));
  return JSON.stringify(data, null, 2);
}

export function exportAsMarkdown(tools: ToolInfo[]): string {
  const lines: string[] = ['# WebMCP Tools', ''];

  for (const tool of tools) {
    lines.push(`## ${tool.name}`);
    if (tool.annotations?.readOnlyHint) lines.push('> Read-only');
    lines.push('', tool.description, '');

    if (tool.inputSchema) {
      const schema = safeParse(tool.inputSchema);
      if (schema?.properties) {
        lines.push('### Parameters', '');
        lines.push('| Name | Type | Required | Description |');
        lines.push('|------|------|----------|-------------|');
        const required = new Set<string>(schema.required ?? []);
        for (const [name, prop] of Object.entries(schema.properties as Record<string, any>)) {
          const type = Array.isArray(prop.type) ? prop.type.join(' | ') : (prop.type ?? 'any');
          const req = required.has(name) ? '✅' : '';
          const desc = (prop.description ?? '').replace(/\|/g, '\\|');
          lines.push(`| \`${name}\` | ${type} | ${req} | ${desc} |`);
        }
        lines.push('');
      }
    }

    lines.push('---', '');
  }

  return lines.join('\n');
}

export function exportAsPostman(tools: ToolInfo[]): string {
  const collection = {
    info: {
      name: 'WebMCP Tools',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    item: tools.map((tool) => {
      const schema = tool.inputSchema ? safeParse(tool.inputSchema) : null;
      const body: Record<string, unknown> = {};
      if (schema?.properties) {
        for (const [name, prop] of Object.entries(schema.properties as Record<string, any>)) {
          const type = Array.isArray(prop.type) ? prop.type[0] : prop.type;
          if (prop.default !== undefined) body[name] = prop.default;
          else if (type === 'string') body[name] = '';
          else if (type === 'number' || type === 'integer') body[name] = 0;
          else if (type === 'boolean') body[name] = false;
          else if (type === 'object') body[name] = {};
          else if (type === 'array') body[name] = [];
        }
      }

      return {
        name: tool.name,
        request: {
          method: 'POST',
          header: [{ key: 'Content-Type', value: 'application/json' }],
          body: {
            mode: 'raw',
            raw: JSON.stringify({ tool: tool.name, args: body }, null, 2),
          },
          url: { raw: `webmcp://execute/${tool.name}`, protocol: 'webmcp', host: ['execute'], path: [tool.name] },
          description: tool.description,
        },
      };
    }),
  };
  return JSON.stringify(collection, null, 2);
}

export function exportAsScriptToolConfig(tools: ToolInfo[]): string {
  const lines: string[] = [
    '// WebMCP Tool Registration Script',
    '// Generated by WebMCP DevTools',
    '',
    'const mc = navigator.modelContext ?? navigator.modelContextTesting;',
    '',
  ];

  for (const tool of tools) {
    const schema = tool.inputSchema ? safeParse(tool.inputSchema) : null;
    const schemaStr = schema ? JSON.stringify(schema, null, 2).replace(/\n/g, '\n    ') : '{}';

    lines.push(`mc.registerTool({`);
    lines.push(`  name: ${JSON.stringify(tool.name)},`);
    lines.push(`  description: ${JSON.stringify(tool.description)},`);
    lines.push(`  inputSchema: ${schemaStr},`);
    lines.push(`  execute: async (args) => {`);
    lines.push(`    // TODO: implement ${tool.name}`);
    lines.push(`    console.log(${JSON.stringify(tool.name)}, args);`);
    lines.push(`    return { success: true };`);
    lines.push(`  },`);
    lines.push(`});`);
    lines.push('');
  }

  return lines.join('\n');
}

function safeParse(input: string | Record<string, unknown>): any {
  if (typeof input === 'object') return input;
  try { return JSON.parse(input); } catch { return null; }
}
